### ISSUE TITLE
[TEMPLATE] Pre-launch Checklist

### ISSUE THREAD

**Issue by ricardomestre** [developmentseed/project-seed#66]
### Content

- [ ] All text free from spelling errors
- [ ] Page and content formatting appropriate on all pages
- [ ] Placeholder text removed
- [ ] All pages have content
- [ ] Favicon retina-ready created and displays correctly: http://www.favicomatic.com/
- [ ] Device icons created and display correctly (Apple touch, Windows tile, etc)
- [ ] Footer includes copyright statement
- [ ] 404 page exists and is informative

### SEO & Analytics

- [ ] Page titles are descriptive and SEO friendly
- [ ] All page titles are unique
- [ ] Meta data included and appropriate
- [ ] humans.txt is generated and added to the root of website
- [ ] Google Analytics and relevant analytics/tracking tools installed

### Social

- [ ] Open Graph tags included across website and appropriate (including images where possible)
- [ ] Twitter Cards tags included across website and appropriate (including image/video/audio where 
 possible)

### Markup

- [ ] HTML has passed validation
- [ ] CSS has passed validation
- [ ] Site links have been tested and resolve correctly
- [ ] JavaScript is error free and linted

### Accessibility

- [ ] ARIA Landmark Roles specified
- [ ] Semantic headings and structure used, attending to HTML5 outline specs: https://gsnedders.html5.org/outliner/
- [ ] Images use appropriate ALT text
- [ ] Associated label for all form controls

### Rendering

- [ ] Displays & functions correctly in all the required browsers
- [ ] Displays & functions correctly on all the required resolutions and devices

### Optimization

- [ ] Images have been optimized: https://compressor.io/
- [ ] CSS is minified and combined
- [ ] JavaScript is minified and combined
- [ ] Enable gzip compression
- [ ] Ensure only necessary fonts, weights and character sets are installed (or embedded if possible)
- [ ] Run Google speed test and optimise accordingly (record score and known issues)

### Post-launch

- [ ] Ensure site is visible to search engines
- [ ] Images, media and links reference live URL
- [ ] Webfonts integrated and working correctly on live site
- [ ] Analytics has been setup and integrated into website
